apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
  namespace: default
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS NAGAP_USER_INFO (
        id SERIAL PRIMARY KEY,
        candidate_name VARCHAR(100) NOT NULL,
        technology_band VARCHAR(100) NOT NULL,
        status VARCHAR(100) NOT NULL
    );
    INSERT INTO NAGAP_USER_INFO (candidate_name, technology_band, status) VALUES
    ('User1', 'TechnologyBand1', 'PotentailNAGP'),
    ('User2', 'TechnologyBand1', 'TaggedNAGAP'),
    ('User3', 'QABand1', 'PotentailNAGP'),
    ('User4', 'QABand1', 'TaggedNAGAP'),
    ('User5', 'ITBand1', 'PotentailNAGP'),
    ('User6', 'ITBand2', 'TaggedNAGAP'),
    ('User7', 'DEVOPSBand1', 'PotentailNAGP'),
    ('User8', 'DEVOPSBand2', 'TaggedNAGAP'),
    ('User9', 'DEVOPSBand2', 'PotentailNAGP'),
    ('User10', 'DEVOPSBand2', 'TaggedNAGAP')
    ON CONFLICT DO NOTHING;
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  namespace: default
spec:
  serviceName: "db-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
        - name: init-volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-volume
        configMap:
          name: db-init-script
  volumeClaimTemplates:
  - metadata:
      name: db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-db